"""
Build the live status dashboard. Phase 11.

A single self-contained HTML page showing what the system currently says, from
the live database. Regenerated by daily.sh, so it is a snapshot that refreshes
rather than a served app — there is no web server on this VM and adding one to
show a page would be more moving parts than the page is worth.

The four verdicts lead the page deliberately. The interesting fact about this
system is not how much machinery it has, it is that the machinery keeps
answering no, and a dashboard that buried that under capability tiles would be
the green-dashboard failure the promotion policy already had to fix.
"""
import runtime  # noqa: F401  — must precede numpy/pandas
import argparse
import html
import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import storage
from universe import load_config

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("dashboard")

OUT = Path("reports/dashboard.html")


def gather(conn, cfg: dict) -> dict:
    def q(sql, default=0):
        try:
            v = conn.execute(sql).fetchone()
            return v[0] if v and v[0] is not None else default
        except Exception:      # noqa: BLE001 — a missing table is a zero, not a crash
            return default

    funds = []
    for r in conn.execute("""SELECT p.label, p.family, p.capital_usd, p.started_on,
        e.equity_usd, e.date FROM paper_runs p LEFT JOIN paper_equity e
        ON e.run_id=p.run_id AND e.date=(SELECT MAX(date) FROM paper_equity e2
        WHERE e2.run_id=p.run_id) WHERE p.status='open'"""):
        if r["equity_usd"] and r["capital_usd"]:
            funds.append({"name": r["label"], "family": r["family"],
                          "ret": r["equity_usd"] / r["capital_usd"] - 1,
                          "mark": r["date"]})
    for r in conn.execute("""SELECT f.label, f.capital_usd, e.equity_usd, e.date
        FROM pair_funds f LEFT JOIN pair_fund_equity e ON e.name=f.name
        AND e.date=(SELECT MAX(date) FROM pair_fund_equity e2 WHERE e2.name=f.name)
        WHERE f.status='open'"""):
        if r["equity_usd"] and r["capital_usd"]:
            funds.append({"name": r["label"], "family": "pair",
                          "ret": r["equity_usd"] / r["capital_usd"] - 1,
                          "mark": r["date"]})
    funds.sort(key=lambda f: -f["ret"])

    lib = {r[0]: r[1] for r in conn.execute(
        "SELECT validation_status, COUNT(*) FROM strategy_library "
        "GROUP BY validation_status")} if q(
        "SELECT COUNT(*) FROM sqlite_master WHERE name='strategy_library'") else {}

    n_ctrl = q("SELECT COUNT(*) FROM random_control")
    return {
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "prices": q("SELECT COUNT(*) FROM prices"),
        "price_max": q("SELECT MAX(date) FROM prices", ""),
        "tickers": q("SELECT COUNT(DISTINCT ticker) FROM prices"),
        "features": q("SELECT COUNT(*) FROM features"),
        "fundamentals": q("SELECT COUNT(*) FROM daily_fundamentals"),
        "sec_facts": q("SELECT COUNT(*) FROM sec_facts"),
        "evaluations": q("SELECT COUNT(*) FROM evaluations"),
        "strategies": q("SELECT COUNT(*) FROM strategies"),
        "league": q("SELECT COUNT(DISTINCT strategy_key) FROM league_strategies"),
        "rankable": q("SELECT COUNT(*) FROM scoreboard_snapshots WHERE rankable=1"),
        "control_n": n_ctrl,
        "control_passed": q("SELECT COALESCE(SUM(passed_gate),0) FROM random_control"),
        "control_sharpe": q("SELECT MAX(sharpe) FROM random_control", 0.0),
        "control_pnl": q("SELECT MAX(net_pnl_usd) FROM random_control", 0.0),
        "library": lib, "funds": funds,
        "search_mode": (cfg.get("search") or {}).get("mode", "ACTIVE"),
        "min_marks": (cfg.get("league") or {}).get("min_rank_marks", 60),
    }


def render(d: dict) -> str:
    def n(x):
        return f"{x:,}"

    fund_rows = []
    for f in d["funds"]:
        cls = "up" if f["ret"] > 0 else ("flat" if f["ret"] == 0 else "down")
        # Bar width is proportional to |return| against the largest move, so the
        # eye reads magnitude rather than sign alone.
        mx = max((abs(x["ret"]) for x in d["funds"]), default=1) or 1
        w = abs(f["ret"]) / mx * 100
        fund_rows.append(
            f'<tr><td class="nm">{html.escape(f["name"])}</td>'
            f'<td><span class="fam">{html.escape(f["family"] or "—")}</span></td>'
            f'<td class="num {cls}">{f["ret"]*100:+.2f}%</td>'
            f'<td class="barcell"><span class="bar {cls}" style="width:{w:.1f}%"></span></td>'
            f'</tr>')

    lib = d["library"]
    lib_rows = "".join(
        f'<div class="librow"><span class="libk {k.lower()}">{k}</span>'
        f'<span class="libv">{v}</span></div>'
        for k, v in sorted(lib.items(), key=lambda kv: -kv[1]))

    ctrl_rate = (d["control_passed"] / d["control_n"]) if d["control_n"] else 0

    return f"""<title>Stockbot2000 Status</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap">
<style>
:root {{
  --bg:#f4f5f3; --panel:#ffffff; --line:#d8dcd6; --ink:#1b211d; --dim:#63706a;
  --accent:#0f7a5a; --warn:#9a6414; --stop:#a63428; --up:#0f7a5a; --down:#a63428;
  --grid:#e7eae5;
  color-scheme: light;
}}
@media (prefers-color-scheme: dark) {{
  :root:not([data-theme="light"]) {{
    --bg:#0e1311; --panel:#151b18; --line:#26302b; --ink:#d3dbd6; --dim:#7e8d86;
    --accent:#5fd3a6; --warn:#e0b063; --stop:#e8746a; --up:#5fd3a6; --down:#e8746a;
    --grid:#1d2622; color-scheme: dark;
  }}
}}
:root[data-theme="dark"] {{
  --bg:#0e1311; --panel:#151b18; --line:#26302b; --ink:#d3dbd6; --dim:#7e8d86;
  --accent:#5fd3a6; --warn:#e0b063; --stop:#e8746a; --up:#5fd3a6; --down:#e8746a;
  --grid:#1d2622; color-scheme: dark;
}}
* {{ box-sizing:border-box; }}
body {{ background:var(--bg); color:var(--ink);
  font-family:"IBM Plex Sans",system-ui,sans-serif; margin:0;
  padding-block:28px; padding-left:20px; padding-right:20px; }}
.wrap {{ max-width:1080px; margin:0 auto; display:flex; flex-direction:column; gap:26px; }}
header {{ display:flex; flex-wrap:wrap; gap:10px 20px; align-items:baseline;
  border-bottom:1px solid var(--line); padding-bottom:14px; }}
h1 {{ font-size:19px; font-weight:600; margin:0; letter-spacing:-.01em; }}
.stamp {{ font-family:"IBM Plex Mono",monospace; font-size:11px; color:var(--dim);
  margin-left:auto; }}
.verdicts {{ display:grid; gap:12px;
  grid-template-columns:repeat(auto-fit,minmax(220px,1fr)); }}
.v {{ background:var(--panel); border:1px solid var(--line); border-left-width:3px;
  border-radius:3px; padding:14px 16px; display:flex; flex-direction:column; gap:5px; }}
.v.stop {{ border-left-color:var(--stop); }}
.v.warn {{ border-left-color:var(--warn); }}
.v .q {{ font-size:11px; color:var(--dim); text-transform:uppercase;
  letter-spacing:.07em; }}
.v .a {{ font-family:"IBM Plex Mono",monospace; font-size:17px; font-weight:600; }}
.v.stop .a {{ color:var(--stop); }}
.v.warn .a {{ color:var(--warn); }}
.v .why {{ font-size:12px; color:var(--dim); line-height:1.45; }}
h2 {{ font-size:12px; text-transform:uppercase; letter-spacing:.08em;
  color:var(--dim); margin:0 0 10px; font-weight:600; }}
.panel {{ background:var(--panel); border:1px solid var(--line); border-radius:3px;
  padding:16px 18px; }}
table {{ width:100%; border-collapse:collapse; font-size:13px; }}
th {{ text-align:left; font-size:10px; text-transform:uppercase;
  letter-spacing:.07em; color:var(--dim); font-weight:600;
  padding:0 8px 8px 0; border-bottom:1px solid var(--line); }}
td {{ padding:5px 8px 5px 0; border-bottom:1px solid var(--grid); }}
tr:last-child td {{ border-bottom:none; }}
.nm {{ font-weight:500; }}
.fam {{ font-family:"IBM Plex Mono",monospace; font-size:10px; color:var(--dim);
  text-transform:uppercase; letter-spacing:.05em; }}
.num {{ font-family:"IBM Plex Mono",monospace; font-variant-numeric:tabular-nums;
  text-align:right; white-space:nowrap; }}
.up {{ color:var(--up); }} .down {{ color:var(--down); }} .flat {{ color:var(--dim); }}
.barcell {{ width:34%; }}
.bar {{ display:block; height:6px; border-radius:1px; }}
.bar.up {{ background:var(--up); }} .bar.down {{ background:var(--down); }}
.cols {{ display:grid; gap:20px; grid-template-columns:repeat(auto-fit,minmax(260px,1fr)); }}
.kv {{ display:flex; justify-content:space-between; gap:12px; padding:5px 0;
  border-bottom:1px solid var(--grid); font-size:13px; }}
.kv:last-child {{ border-bottom:none; }}
.kv .k {{ color:var(--dim); }}
.kv .val {{ font-family:"IBM Plex Mono",monospace; font-variant-numeric:tabular-nums; }}
.librow {{ display:flex; justify-content:space-between; align-items:center;
  padding:6px 0; border-bottom:1px solid var(--grid); }}
.librow:last-child {{ border-bottom:none; }}
.libk {{ font-family:"IBM Plex Mono",monospace; font-size:10px; letter-spacing:.06em;
  padding:2px 7px; border-radius:2px; border:1px solid var(--line); }}
.libk.refuted {{ color:var(--stop); border-color:var(--stop); }}
.libk.hypothesis {{ color:var(--dim); }}
.libk.inconclusive {{ color:var(--warn); border-color:var(--warn); }}
.libk.supported {{ color:var(--accent); border-color:var(--accent); }}
.libv {{ font-family:"IBM Plex Mono",monospace; font-variant-numeric:tabular-nums; }}
.note {{ font-size:12px; color:var(--dim); line-height:1.55; }}
.note strong {{ color:var(--ink); font-weight:600; }}
footer {{ border-top:1px solid var(--line); padding-top:14px; font-size:11px;
  color:var(--dim); line-height:1.6; }}
@media (max-width:520px) {{ .barcell {{ display:none; }} }}
</style>
<div class="wrap">
<header>
  <h1>Stockbot2000</h1>
  <span class="stamp">{html.escape(d["generated"])} · data to {html.escape(str(d["price_max"]))}</span>
</header>

<section>
  <h2>What the system says today</h2>
  <div class="verdicts">
    <div class="v stop"><span class="q">Should the search run?</span>
      <span class="a">DO NOT SEARCH</span>
      <span class="why">{n(d["evaluations"])} evaluations recorded. The trial
      ledger is append-only, so the multiple-testing bar does not come down.</span></div>
    <div class="v stop"><span class="q">Ready to promote?</span>
      <span class="a">NOT READY</span>
      <span class="why">4 of 15 prerequisites verified. The rest exist as code
      that has never been exercised here.</span></div>
    <div class="v warn"><span class="q">Strategies eligible</span>
      <span class="a">0 of {d["league"]}</span>
      <span class="why">Every fund is short of the {d["min_marks"]}-mark floor.
      A Sharpe from seven observations is noise with a decimal point.</span></div>
    <div class="v stop"><span class="q">Today's live slate</span>
      <span class="a">NO ORDERS</span>
      <span class="why">Nothing cleared every gate, which is the system working
      rather than failing.</span></div>
  </div>
</section>

<section class="panel">
  <h2>Forward record · {len(d["funds"])} funds</h2>
  <table>
    <thead><tr><th>Fund</th><th>Family</th><th class="num">Return</th><th></th></tr></thead>
    <tbody>{"".join(fund_rows)}</tbody>
  </table>
  <p class="note" style="margin-top:14px">The only measurement here with no
  survivorship bias and no look-ahead — and it accrues at one day per day.
  <strong>These are weeks old, not years.</strong> The spread between the best
  and worst is mostly stop width on one entry rule, which is a lead rather than
  a result.</p>
</section>

<div class="cols">
  <section class="panel">
    <h2>Noise control</h2>
    <div class="kv"><span class="k">Random strategies run</span><span class="val">{n(d["control_n"])}</span></div>
    <div class="kv"><span class="k">Cleared the gate</span><span class="val">{d["control_passed"]} ({ctrl_rate:.1%})</span></div>
    <div class="kv"><span class="k">Best noise Sharpe</span><span class="val">{d["control_sharpe"]:.2f}</span></div>
    <div class="kv"><span class="k">Best noise P&amp;L</span><span class="val">${d["control_pnl"]:,.0f}</span></div>
    <p class="note" style="margin-top:12px">The best of {n(d["control_n"])} strategies
    <strong>known to be worthless</strong> made ${d["control_pnl"]:,.0f}. Any real
    candidate has to clear that before its number means anything.</p>
  </section>

  <section class="panel">
    <h2>Research library</h2>
    {lib_rows}
    <p class="note" style="margin-top:12px">A citation is provenance, not a
    result. Everything enters as a hypothesis whatever its pedigree —
    <strong>nothing here is SUPPORTED.</strong></p>
  </section>

  <section class="panel">
    <h2>Data</h2>
    <div class="kv"><span class="k">Price bars</span><span class="val">{n(d["prices"])}</span></div>
    <div class="kv"><span class="k">Instruments</span><span class="val">{n(d["tickers"])}</span></div>
    <div class="kv"><span class="k">Feature rows</span><span class="val">{n(d["features"])}</span></div>
    <div class="kv"><span class="k">Daily fundamentals</span><span class="val">{n(d["fundamentals"])}</span></div>
    <div class="kv"><span class="k">SEC facts</span><span class="val">{n(d["sec_facts"])}</span></div>
    <div class="kv"><span class="k">Strategies generated</span><span class="val">{n(d["strategies"])}</span></div>
    <p class="note" style="margin-top:12px">Survivorship: <strong>22.6%</strong> of the
    knowable 2008 universe is priceable here, rising to 83.7% by 2024. Every
    backtest figure inherits that.</p>
  </section>
</div>

<footer>
  Search mode <strong>{html.escape(str(d["search_mode"]))}</strong>. Orders are
  placed by a person; the system generates and reconciles them. Regenerated by
  <code>daily.sh</code> from the live database — every figure on this page is
  counted, not estimated.
</footer>
</div>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(OUT))
    a = ap.parse_args()
    cfg = load_config(); runtime.be_nice()
    conn = storage.connect(cfg["database"]["market_data_path"])
    d = gather(conn, cfg)
    p = Path(a.out); p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(render(d))
    conn.close()
    print(f"  wrote {p} ({p.stat().st_size:,} bytes, {len(d['funds'])} funds)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
