"""
The twin test (Stage M5; docs/STAGE_M_RESEARCH.md §5.3): do synthetic dead
companies TRADE like real ones?

The realism gate (validate_v5.py) asks whether a classifier can tell a
synthetic path from a real one. This asks the question the ranking depends
on: would the strategies we rank have earned, on a synthetic twin, what they
earned on the real company?

    real   dead companies whose prices we hold:
             failures  the distress donors that died (distress_donors.py)
             buyouts   the real dead sample v4 copies (cohort_sample_v1, mostly acquisitions)
    twin   the same company generated by the SAME generator code as the
           synthetic set (universe_synthetic_v5.failure / universe_synthetic.generate),
           on the real company's own dates, from every OTHER donor — leave one
           out, so a twin never copies its own real path
    trade  every non-fundamental pool strategy (survivorship_backtest.strategies)
           through the real simulator, costs and next-open fills, on the real
           panel and on the twin panel separately; same feature code on both,
           volume treated as unknown on both (twins have none)

Both sides end at the LAST TRADED price: the twin's delisting bar is dropped,
because the real series in free data stops before its delisting return too.
That return is a separate, literature-calibrated assumption (Shumway), not
something this test can check.

Pre-registered (experiment `twin_test_v5`, written before the first run):
the twins are "trade-realistic" for a kind if the pooled mean net return per
trade differs from the real one by less than 0.5 percentage points AND the
95% company-cluster bootstrap interval of the difference contains zero.

    ./run_bounded.sh ./venv/bin/python twin_test.py --run
"""
import runtime  # noqa: F401  — must precede numpy/pandas
import argparse
import json
import logging
import os
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

log = logging.getLogger("twin_test")
OUT = Path("data/universe/twin_test.json")
EXPERIMENT = "twin_test_v5"
MAX_DIFF = 0.005
BOOT = 2000


def _ohlcv(conn, fconn, ticker: str, source: str) -> pd.DataFrame:
    if source == "primary" or fconn is None:
        q = "SELECT date, open, high, low, close FROM prices WHERE ticker=? ORDER BY date"
        df = pd.read_sql_query(q, conn, params=(ticker,))
    else:
        q = "SELECT date, open, high, low, close FROM finsaber_prices WHERE symbol=? ORDER BY date"
        df = pd.read_sql_query(q, fconn, params=(ticker,))
    df["date"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
    return df.dropna().query("close > 0").drop_duplicates("date")


def _clip_life(df: pd.DataFrame, spy: pd.Series, max_years: int) -> pd.DataFrame:
    """The real company on SPY's dates, over the life a synthetic company would get."""
    df = df[df["date"].isin(spy.index)]
    if df.empty:
        return df
    last = df["date"].iloc[-1]
    first = max(df["date"].iloc[0], (pd.Timestamp(last) - pd.DateOffset(years=max_years)).date().isoformat())
    return df[df["date"] >= first].reset_index(drop=True)


def failure_pairs(conn, cfg, spy, v4donors) -> list:
    """(ticker, real OHLC, twin OHLC) for every real failure we price."""
    import universe_synthetic as v4
    import universe_synthetic_v5 as v5
    s4, s = v4.settings(cfg), v5.settings(cfg)
    ddf = pd.read_parquet("data/universe/distress_donors.parquet")
    dd = [{"year": int(r.year), "died": bool(r.died), "beta": float(r.beta), "a_offset": int(r.a_offset),
           "t_offset": int(r.t_offset), "resid": json.loads(r.resid), "ret": json.loads(r.ret),
           "price_a": float(r.price_a), "fall": float(r.fall_a_to_t), "ticker": r.ticker, "exchange": r.exchange}
          for r in ddf.itertuples()]
    out = []
    for R in [d for d in dd if d["died"]]:
        real = _clip_life(_ohlcv(conn, None, R["ticker"], "primary"), spy, s4["max_years"])
        if len(real) < 60:
            continue
        pool = [d for d in dd if d["ticker"] != R["ticker"]]              # leave one out
        post = [(np.asarray(x["resid"][x["t_offset"] + 1:], dtype=float),
                 np.abs(np.asarray(x["ret"][x["t_offset"] + 1:], dtype=float)) < 1e-6,
                 np.asarray(x["ret"][x["t_offset"] + 1:], dtype=float)) for x in pool
                if x["died"] and len(x["resid"]) - x["t_offset"] > 20]
        dates = pd.Index(real["date"])
        rng = np.random.default_rng(v4.seed_for("twin:" + R["ticker"], s4["seed"]) + 5)
        r, e, a_idx, dn = v5.failure({}, spy, v4donors, v5.failure_donor_pool(pool, s), post, s, rng, dates, True)
        # Same price assembly as universe_synthetic_v5.build (the donor's own level at its last $5 close).
        growth = np.cumprod(1 + r)
        close = np.maximum(float(dn["price_a"]) * growth / growth[a_idx], 0.01)
        prev = np.concatenate([[close[0]], close[:-1]])
        wid = np.abs(e) / 2
        twin = pd.DataFrame({"date": dates, "open": prev, "high": np.maximum(close, prev) * (1 + wid),
                             "low": np.minimum(close, prev) * (1 - wid), "close": close})
        out.append((R["ticker"], real, twin, dn["ticker"]))
    return out


def buyout_pairs(conn, cfg, spy) -> tuple:
    """(pairs, v4 donors): the real dead sample and v4 twins from every other donor."""
    import universe_cohorts as uc
    import universe_synthetic as v4
    s4 = v4.settings(cfg)
    sample = pd.read_parquet("data/universe/cohort_sample_v1.parquet")
    fconn = sqlite3.connect("file:data/finsaber.db?mode=ro", uri=True) if os.path.exists("data/finsaber.db") else None
    by_ticker = {}
    for i in range(len(sample)):
        d = v4.donor_residuals(conn, sample.iloc[[i]], spy)
        if d:
            by_ticker[sample.iloc[i]["ticker"]] = d[0]
    donors = list(by_ticker.values())
    art = json.load(open(uc.OUT))
    starts = np.array([c for (c,) in conn.execute(
        "SELECT close FROM (SELECT p.ticker, p.close, MIN(p.date) FROM prices p JOIN symbols s ON "
        "s.ticker=p.ticker WHERE s.security_type='common_stock' AND p.close>0 GROUP BY p.ticker)")])
    out = []
    for row in sample.itertuples():
        if row.ticker not in by_ticker:
            continue
        real = _clip_life(_ohlcv(conn, fconn, row.ticker, row.source), spy, s4["max_years"])
        if len(real) < 60:
            continue
        pool = [d for t, d in by_ticker.items() if t != row.ticker]      # leave one out
        c = {"company_id": "twin:" + row.ticker, "ticker": "twin:" + row.ticker,
             "first_seen": real["date"].iloc[0], "last_seen": real["date"].iloc[-1],
             "sic": None, "delisting_reason": None, "exchange": None}
        twin = v4.generate(c, spy, pool, art, starts, {**s4, "exit_prior": {"merger": 1.0}})
        if twin.empty:
            continue
        twin = twin[~twin["is_delisting_bar"]][["date", "open", "high", "low", "close"]]
        twin["date"] = pd.Index(twin["date"]).astype(str)
        out.append((row.ticker, real, twin.reset_index(drop=True), None))
    if fconn:
        fconn.close()
    return out, donors


def _frames(named: list, cfg) -> tuple:
    """Feature rows (entry candidates) and exit prices, the way survivorship_backtest builds synthetic ones."""
    import features
    import survivorship_backtest as sb
    from train_model import FEATURE_COLS
    floor = float(cfg["risk"].get("min_dollar_volume") or 1e6)
    min_price = float(cfg["risk"].get("min_price") or 0)
    parts = []
    for name, df in named:
        g = df.assign(ticker=name, volume=np.nan, date=pd.to_datetime(df["date"]))
        f = features.compute_features_for_ticker(g[["ticker", "date", "open", "high", "low", "close", "volume"]],
                                                 min_rows=sb.MIN_SYNTH_ROWS)
        if not f.empty:
            parts.append(f)
    f = pd.concat(parts, ignore_index=True)
    for c in sb.VOLUME_COLS:
        f[c] = np.nan
    f["dollar_volume_20"] = floor
    f["log_dollar_volume"] = np.log10(floor)
    exits = f[["ticker", "date", "close", "open"]].copy()
    need = [c for c in FEATURE_COLS if c not in sb.VOLUME_COLS]
    rows = f[f["close"] >= min_price].dropna(subset=need)
    rows = rows[["ticker", "date", "close", "open", *FEATURE_COLS, "dollar_volume_20"]].copy()
    for df in (rows, exits):
        df["ticker"] = df["ticker"].astype("category")
    return rows, exits


def _trades(strats, rows, exits, cfg) -> pd.DataFrame:
    """One row per trade: strategy, company, net return per dollar."""
    import costs as costs_mod
    import simulator
    if rows.empty:
        return pd.DataFrame(columns=["strategy", "company", "ret"])
    panel = simulator.Panel(rows, exit_prices=exits)
    size = float(cfg["risk"]["position_size_usd"])
    cap = int((cfg.get("factory") or {}).get("max_entries_per_backtest", 5000))
    cm = costs_mod.CostModel(cfg)
    tick = panel.df["ticker"].astype(str).to_numpy()
    out = []
    for key, ver, g, _ in strats:
        try:
            r = simulator.simulate(g, panel, cm, size, max_entries=cap)
        except Exception as e:                                   # noqa: BLE001
            log.warning(f"{key} v{ver}: {type(e).__name__}: {e}")
            continue
        if r["n_trades"]:
            comp = [t.split(":", 1)[1] for t in tick[r["entry_rows"]]]
            out.append(pd.DataFrame({"strategy": f"{key} v{ver}", "company": comp,
                                     "ret": np.asarray(r["pnl_series"], dtype=float) / size}))
    return pd.concat(out, ignore_index=True) if out else pd.DataFrame(columns=["strategy", "company", "ret"])


def compare(real: pd.DataFrame, twin: pd.DataFrame, companies: list, seed: int = 7) -> dict:
    """Pooled per-trade comparison with a company-cluster bootstrap of the difference."""
    from scipy.stats import ks_2samp
    res = {"trades_real": int(len(real)), "trades_twin": int(len(twin)),
           "companies": len(companies),
           "companies_traded_real": int(real["company"].nunique()) if len(real) else 0,
           "companies_traded_twin": int(twin["company"].nunique()) if len(twin) else 0}
    if not len(real) or not len(twin):
        return {**res, "verdict": "no trades on one side — not measurable"}
    res.update({"mean_real": float(real["ret"].mean()), "mean_twin": float(twin["ret"].mean()),
                "median_real": float(real["ret"].median()), "median_twin": float(twin["ret"].median()),
                "win_real": float((real["ret"] > 0).mean()), "win_twin": float((twin["ret"] > 0).mean())})
    res["diff"] = res["mean_twin"] - res["mean_real"]
    ks = ks_2samp(real["ret"], twin["ret"])
    res["ks_stat"], res["ks_p_naive"] = float(ks.statistic), float(ks.pvalue)
    rg = {c: g["ret"].to_numpy() for c, g in real.groupby("company")}
    tg = {c: g["ret"].to_numpy() for c, g in twin.groupby("company")}
    rng = np.random.default_rng(seed)
    comp = np.array(companies)
    diffs = []
    for _ in range(BOOT):
        pick = comp[rng.integers(len(comp), size=len(comp))]
        a = [rg[c] for c in pick if c in rg]
        b = [tg[c] for c in pick if c in tg]
        if a and b:
            diffs.append(np.concatenate(b).mean() - np.concatenate(a).mean())
    lo, hi = np.percentile(diffs, [2.5, 97.5])
    res["diff_ci95"] = [float(lo), float(hi)]
    ok = abs(res["diff"]) < MAX_DIFF and lo <= 0 <= hi
    res["verdict"] = "PASS" if ok else "FAIL"
    return res


def per_strategy(real: pd.DataFrame, twin: pd.DataFrame) -> list:
    a = real.groupby("strategy")["ret"].agg(["count", "mean"]).rename(columns={"count": "n_real", "mean": "real"})
    b = twin.groupby("strategy")["ret"].agg(["count", "mean"]).rename(columns={"count": "n_twin", "mean": "twin"})
    j = a.join(b, how="outer").reset_index()
    return json.loads(j.to_json(orient="records"))


def _gen_key(v5) -> str:
    """The generator method plus the settings that change failure paths."""
    from universe import load_config
    st = v5.settings(load_config())
    return f"{v5.METHOD}|total_returns={st.get('donor_total_returns')}|failure_donors={st.get('failure_donors')}"


def register(conn) -> None:
    """Pre-register once per generator method; a new method is a new version, never an edit."""
    import experiment_registry as er
    import universe_synthetic_v5 as v5
    try:
        e = er.get(conn, EXPERIMENT)
        if json.loads(e["spec"]).get("generator") == _gen_key(v5):
            return
        make = lambda h, spec: er.new_version(conn, EXPERIMENT, h, "claude", spec,   # noqa: E731
                                              f"generator changed to {_gen_key(v5)}")
    except er.RegistryError:
        make = lambda h, spec: er.create(conn, EXPERIMENT, h, "claude", spec)        # noqa: E731
    make(
              "Synthetic twins generated by generator v5 (leave-one-out donors, the real company's own dates) earn "
              "what the real dead companies earned under the ranked strategies. Fails for a kind (failures / "
              "buyouts) if the pooled mean net return per trade differs by 0.5 pp or more, or the 95% "
              "company-cluster bootstrap interval of the difference excludes zero.",
              {"generator": _gen_key(v5), "real": "distress donors that died + cohort_sample_v1", "strategies": "survivorship_backtest.strategies, "
               "non-fundamental", "fills": "simulator (next open), costs.CostModel", "volume": "unknown on both sides",
               "delisting_bar": "dropped on both sides", "max_diff": MAX_DIFF, "bootstrap": BOOT})
    er.register(conn, EXPERIMENT)
    er.start(conn, EXPERIMENT)


# --- Stage M2b: anchoring twins to their own company's filed prices ---------------

ANCHOR_EXPERIMENT = "twin_test_anchors"


def anchors_for(conn, cik) -> list:
    """[(period_end, high, low)] filed for this company, the newest filing's figure per quarter."""
    if cik is None:
        return []
    rows = conn.execute("SELECT period_end, high, low, filed FROM item5_anchors WHERE cik=? "
                        "ORDER BY period_end, filed DESC", (int(cik),)).fetchall()
    out, seen = [], set()
    for pe, hi, lo, _ in rows:
        if pe not in seen:
            seen.add(pe)
            out.append((pe, float(hi), float(lo)))
    return out


def cik_of(conn, ticker: str, company_id: str | None = None):
    if company_id and str(company_id).startswith("CIK"):
        return int(str(company_id)[3:])
    r = conn.execute("SELECT cik FROM sec_filings WHERE ticker=? GROUP BY cik ORDER BY COUNT(*) DESC LIMIT 1",
                     (ticker,)).fetchone()
    return int(r[0]) if r else None


def anchored(twin: pd.DataFrame, anchors: list) -> tuple:
    import universe_synthetic_v5 as v5
    f, n = v5.anchor_factor(twin["date"], twin["close"], anchors)
    if not n:
        return twin, 0
    out = twin.copy()
    for c in ("open", "high", "low", "close"):
        out[c] = out[c].to_numpy() * f
    return out, n


def register_anchors(conn) -> None:
    import experiment_registry as er
    try:
        er.get(conn, ANCHOR_EXPERIMENT)
        return
    except er.RegistryError:
        pass
    er.create(conn, ANCHOR_EXPERIMENT,
              "Rescaling a twin's price level onto its own company's filed 10-K Item 5 quarterly high/low "
              "(universe_synthetic_v5.anchor_factor) moves its mean net return per trade CLOSER to the real "
              "company's than the unanchored twin, on the companies with at least two filed quarters inside "
              "their path. Fails if |anchored - real| >= |unanchored - real| for a kind.", "claude",
              {"subset": "twin-test companies with >= 2 anchors in path", "method": "anchor_factor, log-linear "
               "interpolation of filed/path quarter mids", "anchors": "item5_anchors (10-Ks filed before 2019)"})
    er.register(conn, ANCHOR_EXPERIMENT)
    er.start(conn, ANCHOR_EXPERIMENT)


def anchored_subset(conn, cfg, strats, pairs, cids: dict) -> dict:
    sub = []
    for t, real, twin, _ in pairs:
        a = anchors_for(conn, cik_of(conn, t, cids.get(t)))
        tw, n = anchored(twin, a)
        if n >= 2:
            sub.append((t, real, twin, tw, n))
    if not sub:
        return {"companies": 0}
    names = [t for t, *_ in sub]
    rr, re_ = _frames([(f"R:{t}", r) for t, r, _, _, _ in sub], cfg)
    ur, ue = _frames([(f"T:{t}", w) for t, _, w, _, _ in sub], cfg)
    ar, ae = _frames([(f"T:{t}", w) for t, _, _, w, _ in sub], cfg)
    a, b, c = _trades(strats, rr, re_, cfg), _trades(strats, ur, ue, cfg), _trades(strats, ar, ae, cfg)
    unan, anch = compare(a, b, names), compare(a, c, names)
    closer = (abs(anch["diff"]) < abs(unan["diff"])) if "diff" in anch and "diff" in unan else None
    return {"companies": len(sub), "anchors_median": float(np.median([n for *_, n in sub])),
            "unanchored": {k: unan.get(k) for k in ("mean_real", "mean_twin", "diff", "diff_ci95", "verdict")},
            "anchored": {k: anch.get(k) for k in ("mean_real", "mean_twin", "diff", "diff_ci95", "verdict")},
            "price_real_median": float(np.median([r["close"].median() for _, r, *_ in sub])),
            "price_unanchored_median": float(np.median([w["close"].median() for _, _, w, _, _ in sub])),
            "price_anchored_median": float(np.median([w["close"].median() for *_, w, _ in sub])),
            "anchoring_moves_closer": closer}


def run(conn, cfg) -> dict:
    import survivorship_backtest as sb
    import universe_synthetic as v4
    register(conn)
    spy = pd.read_sql_query("SELECT date, close FROM prices WHERE ticker='SPY' ORDER BY date", conn
                            ).set_index("date")["close"]
    strats = [s for s in sb.strategies(conn) if not s[3]]
    log.info(f"{len(strats)} non-fundamental strategies")
    buys, donors = buyout_pairs(conn, cfg, spy)
    fails = failure_pairs(conn, cfg, spy, donors)
    report = {"at": datetime.now(timezone.utc).isoformat(timespec="seconds"), "experiment": EXPERIMENT,
              "strategies": len(strats), "generator": "v5 (failures) / v4 final-year donor (buyouts, as v5 uses)"}
    register_anchors(conn)
    sample = pd.read_parquet("data/universe/cohort_sample_v1.parquet")
    cids = dict(zip(sample["ticker"], sample["company_id"]))
    for kind, pairs in (("failures", fails), ("buyouts", buys)):
        rr, re_ = _frames([(f"R:{t}", real) for t, real, _, _ in pairs], cfg)
        tr, te = _frames([(f"T:{t}", twin) for t, _, twin, _ in pairs], cfg)
        a, b = _trades(strats, rr, re_, cfg), _trades(strats, tr, te, cfg)
        report[kind] = {**compare(a, b, [t for t, _, _, _ in pairs]), "by_strategy": per_strategy(a, b),
                        "rows_real": int(len(rr)), "rows_twin": int(len(tr)),
                        "price_real_median": float(np.median([p[1]["close"].median() for p in pairs])),
                        "price_twin_median": float(np.median([p[2]["close"].median() for p in pairs]))}
        report[kind]["anchored_subset"] = anchored_subset(conn, cfg, strats, pairs,
                                                          cids if kind == "buyouts" else {})
        log.info(f"{kind}: {report[kind].get('verdict')}  real {report[kind].get('mean_real')}  "
                 f"twin {report[kind].get('mean_twin')}")
    OUT.write_text(json.dumps(report, indent=1, default=str))
    try:
        er_res = {k: report[k]["anchored_subset"] for k in ("failures", "buyouts")}
        import experiment_registry as er2
        er2.complete(conn, ANCHOR_EXPERIMENT, er_res,
                     "; ".join(f"{k}: closer={v.get('anchoring_moves_closer')}" for k, v in er_res.items()))
    except Exception as e:                                       # noqa: BLE001
        log.warning(f"anchor registry: {type(e).__name__}: {e}")
    import experiment_registry as er
    try:
        er.complete(conn, EXPERIMENT, {k: {x: report[k].get(x) for x in ("verdict", "mean_real", "mean_twin",
                                                                          "diff", "diff_ci95", "trades_real",
                                                                          "trades_twin")}
                                       for k in ("failures", "buyouts")} | {"file": str(OUT)},
                    f"failures {report['failures'].get('verdict')}, buyouts {report['buyouts'].get('verdict')}")
    except Exception as e:                                       # noqa: BLE001 — a re-run of a completed experiment
        log.warning(f"registry: {type(e).__name__}: {e}")
    return report


def render(rep: dict) -> str:
    def p(v):
        return "     —" if v is None else f"{v:+.2%}"
    L = ["", f"  TWIN TEST ({rep['experiment']}) — {rep['strategies']} strategies, same simulator/costs/fills",
         f"  {'kind':<9} {'cos':>4} {'trades R/T':>12} {'mean R':>8} {'mean T':>8} {'diff':>8} "
         f"{'95% CI':>18} {'median $ R/T':>13}  verdict"]
    for k in ("failures", "buyouts"):
        r = rep[k]
        ci = r.get("diff_ci95")
        L.append(f"  {k:<9} {r['companies']:>4} {r['trades_real']:>6}/{r['trades_twin']:<5} {p(r.get('mean_real')):>8} "
                 f"{p(r.get('mean_twin')):>8} {p(r.get('diff')):>8} "
                 f"{('[' + p(ci[0]) + ',' + p(ci[1]) + ']') if ci else '—':>18} "
                 f"{r['price_real_median']:>6.2f}/{r['price_twin_median']:<6.2f}  {r['verdict']}")
    for k in ("failures", "buyouts"):
        a = rep[k].get("anchored_subset") or {}
        if a.get("companies"):
            L.append(f"  {k} with filed anchors ({a['companies']} cos, median {a['anchors_median']:.0f} quarters): "
                     f"real {p(a['anchored']['mean_real'])}  twin {p(a['unanchored']['mean_twin'])} -> anchored "
                     f"{p(a['anchored']['mean_twin'])}   price ${a['price_real_median']:.2f} real, "
                     f"${a['price_unanchored_median']:.2f} -> ${a['price_anchored_median']:.2f} twin   "
                     f"closer: {a['anchoring_moves_closer']}")
    return "\n".join(L)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run", action="store_true")
    a = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    from universe import load_config
    cfg = load_config()
    conn = sqlite3.connect(cfg["database"]["market_data_path"], timeout=60)
    conn.row_factory = sqlite3.Row
    if a.run:
        print(render(run(conn, cfg)))
    elif OUT.exists():
        print(render(json.loads(OUT.read_text())))
    return 0


if __name__ == "__main__":
    sys.exit(main())
